// <auto-generated />
using System;
using AkilliMesaiPlanlayici.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AkilliMesaiPlanlayici.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250512065148_AddMeslekAndMaasToPersonel")]
    partial class AddMeslekAndMaasToPersonel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AkilliMesaiPlanlayici.Models.FazlaMesai", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("GercekBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GercekBitis")
                        .HasColumnType("datetime2");

                    b.Property<string>("Neden")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OnayDurumu")
                        .HasColumnType("bit");

                    b.Property<int>("PersonelID")
                        .HasColumnType("int");

                    b.Property<decimal>("SaatSayisi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("PersonelID");

                    b.ToTable("FazlaMesaier");
                });

            modelBuilder.Entity("AkilliMesaiPlanlayici.Models.Meslek", b =>
                {
                    b.Property<int>("MeslekID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeslekID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OrtalamaMaas")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MeslekID");

                    b.ToTable("Meslek");
                });

            modelBuilder.Entity("AkilliMesaiPlanlayici.Models.Personel", b =>
                {
                    b.Property<int>("PersonelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelID"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AylikMaas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Birim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<int>("MeslekID")
                        .HasColumnType("int");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonelID");

                    b.HasIndex("MeslekID");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("AkilliMesaiPlanlayici.Models.PersonelVardiya", b =>
                {
                    b.Property<int>("PersonelVardiyaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelVardiyaID"));

                    b.Property<DateTime>("GercekBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GercekBitis")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonelID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("VardiyaID")
                        .HasColumnType("int");

                    b.HasKey("PersonelVardiyaID");

                    b.HasIndex("PersonelID");

                    b.HasIndex("VardiyaID");

                    b.ToTable("PersonelVardiyalar");
                });

            modelBuilder.Entity("AkilliMesaiPlanlayici.Models.Vardiya", b =>
                {
                    b.Property<int>("VardiyaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VardiyaID"));

                    b.Property<TimeSpan>("BaslangicSaati")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("BitisSaati")
                        .HasColumnType("time");

                    b.Property<string>("VardiyaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VardiyaID");

                    b.ToTable("Vardiyalar");
                });

            modelBuilder.Entity("AkilliMesaiPlanlayici.Models.FazlaMesai", b =>
                {
                    b.HasOne("AkilliMesaiPlanlayici.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("AkilliMesaiPlanlayici.Models.Personel", b =>
                {
                    b.HasOne("AkilliMesaiPlanlayici.Models.Meslek", "Meslek")
                        .WithMany()
                        .HasForeignKey("MeslekID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meslek");
                });

            modelBuilder.Entity("AkilliMesaiPlanlayici.Models.PersonelVardiya", b =>
                {
                    b.HasOne("AkilliMesaiPlanlayici.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AkilliMesaiPlanlayici.Models.Vardiya", "Vardiya")
                        .WithMany()
                        .HasForeignKey("VardiyaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("Vardiya");
                });
#pragma warning restore 612, 618
        }
    }
}
